### ISSUE TITLE
segfault if section name does not contain a .

### ISSUE THREAD

**Issue by bapt** [mpieuchot/ctfconv#1]
https://github.com/mpieuchot/ctfconv/blob/3a2a8c8bd0f317c543357dad72b6dedfb118e0bb/ctfconv.c#L289

Which makes it segfault when running on the freebsd kernel

**Comment by mpieuchot** [comment]
Should be fixed in bad19bc5ccb0c1fef68f198bcd0931178ccd7fec

Do not hesitate to include a traceback when you encounter a segfault.

**Comment by mpieuchot** [comment]
Fix confirmed my Mark Johnston, markj@FreeBSD
